# Generated by Django 3.0.3 on 2020-03-07 03:58

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_to_coc', models.BooleanField(null=True, verbose_name='Do you agree to the Code of Conduct?')),
                ('allergens_severe', models.TextField(help_text='List allergens that would be a threat to you if they were in the venue at all', max_length=828, null=True, verbose_name='Severe Allergies')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DjangoSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_session',
            field=models.OneToOneField(default=registration.models.UserSession.get_current_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.UserSession'),
        ),
    ]
