# Generated by Django 3.0.4 on 2020-03-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField()),
                ('max_quantity_per_reg', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='allergens_severe',
            field=models.TextField(help_text='List allergens that would be a threat to you if they were in the venue at all', max_length=1000, null=True, verbose_name='Severe Allergies'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registration.Product'),
            preserve_default=False,
        ),
    ]
