# Generated by Django 3.0.4 on 2020-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200307_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='APFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('last_updated', models.TimeField(auto_now=True)),
            ],
        ),
    ]
